name: example
description: "A Flutter project to demonstrate the use of the magic_the_gathering_flutter package."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  magic_the_gathering_flutter:
    path: ../

dev_dependencies:
  very_good_analysis: ^11.0.0

flutter:
  assets:
    - assets/
