name: magic_the_gathering_flutter
description: "Develop Magic: The Gathering Flutter apps with ease. Fully interoperable with the Scryfall API or your own custom JSON."
repository: https://github.com/zmuranaka/magic_the_gathering_flutter
issue_tracker: https://github.com/zmuranaka/magic_the_gathering_flutter/issues
version: 2.0.5

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  mtg_symbology: ^1.0.6

dev_dependencies:
  test: ^1.31.2
  very_good_analysis: ^10.3.0
